name: python3.14
on: [push]
jobs:
    build:
      name: Ubuntu (Python3.14)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Python 3.14
          uses: actions/setup-python@v5
          with:
            python-version: '3.14'
        - name: Install UV
          run: python -m pip install uv
        - name: Run Unit Tests
          run: uv run pytest --cov=enigma
        - name: Run Bandit
          run: uv run bandit -r enigma -c pyproject.toml